### PR TITLE
Fix Space#moveWindows on Sonoma 14.5.

### LINKED ISSUE #348: space(i).moveWindows([x]) seems to no longer work under Sonoma 14.5
- Version: 4.0.0
- macOS: Sonoma 14.5

Example:
`space(i).moveWindows([ACTIVE_WINDOW])`

I think Sonoma 14.5 had some big GUI engine updates, so it's likely related to this upgrade.
Not seeing any errors in the Phoenix logs. It finds the active window and the space.

I am seeing:
```
2024-05-15 12:02:04.787165-0400 0x238d7    Default     0x0                  26641  0    Phoenix: Info: Could not get value for attribute “AXWindow” from element <AXUIElement 0x60000167afa0> {pid=33874}. (-25205)
2024-05-15 12:02:04.868653-0400 0x238d7    Default     0x0                  26641  0    Phoenix: Info: Could not get value for attribute “AXWindow” from element <AXUIElement 0x60000167b2a0> {pid=33874}. (-25205)
2024-05-15 12:02:04.914860-0400 0x238d7    Default     0x0                  26641  0    Phoenix: Info: Could not get value for attribute “AXWindow” from element <AXUIElement 0x60000165b000> {pid=33874}. (-25205)
2024-05-15 12:02:06.312426-0400 0x238d7    Default     0x0                  26641  0    Phoenix: Info: Could not get value for attribute “AXWindow” from element <AXUIElement 0x600001653c60> {pid=33874}. (-25205)
2024-05-15 12:02:19.402839-0400 0x238d7    Default     0x0                  26641  0    Phoenix: Info: Could not get value for attribute “AXWindow” from element <AXUIElement 0x60000165a940> {pid=33874}. (-25205)
2024-05-15 12:02:19.464484-0400 0x238d7    Default     0x0                  26641  0    Phoenix: Info: Could not get value for attribute “AXWindow” from element <AXUIElement 0x60000167f840> {pid=33874}. (-25205)
2024-05-15 12:02:19.507296-0400 0x238d7    Default     0x0                  26641  0    Phoenix: Info: Could not get value for attribute “AXWindow” from element <AXUIElement 0x600001604060> {pid=33874}. (-25205)
2024-05-15 12:02:21.153676-0400 0x238d7    Default     0x0                  26641  0    Phoenix: Info: Could not get value for attribute “AXWindow” from element <AXUIElement 0x600001679da0> {pid=33874}. (-25205)
```

... which may be related to the problem?

### PR DESCRIPTION
**Pull request by metakirby5**
- [x] Updated related documentations
- [x] Added the change to the Changelog

 Introduce a workaround to CGSMoveWindowsToManagedSpace breaking in MacOS 14.5, based on:

- https://github.com/koekeishiya/yabai/issues/2240#issuecomment-2116326165
- https://github.com/ianyh/Amethyst/issues/1643#issuecomment-2132519682

Fixes #348 and #349.

### CODE REVIEW

File: Phoenix/PHSpace.m [hunk 1]
```diff
@@ -61,8 +65,25 @@ @implementation PHSpace
...
 void CGSMoveWindowsToManagedSpace(CGSConnectionID connection, CFArrayRef windowIds, CGSSpaceID spaceId);
 
+/**
+ * The two functions below serve as a workaround to CGSMoveWindowsToManagedSpace breaking in MacOS 14.5.
+ * - https://github.com/kasper/phoenix/issues/348
+ * - https://github.com/koekeishiya/yabai/issues/2240#issuecomment-2116326165
+ * - https://github.com/ianyh/Amethyst/issues/1643#issuecomment-2132519682
+ */
+
+// XXX: Undocumented private API to set a space's (legacy) compatID
```
Comment (kasper) [inline Phoenix/PHSpace.m:78]:
```suggestion
// XXX: Undocumented private API to set a space’s (legacy) compatId
```

File: Phoenix/PHSpace.m [hunk 2]
```diff
@@ -61,8 +65,25 @@ @implementation PHSpace
...
+CGError CGSSpaceSetCompatID(CGSConnectionID connection, CGSSpaceID spaceId, NSUInteger compatID);
```
Comment (kasper) [inline Phoenix/PHSpace.m:79]:
```suggestion
CGError CGSSpaceSetCompatID(CGSConnectionID connection, CGSSpaceID spaceId, NSUInteger compatId);
```

File: Phoenix/PHSpace.m [hunk 3]
```diff
@@ -61,8 +65,25 @@ @implementation PHSpace
...
+
+// XXX: Undocumented private API to move the given windows (CGWindowIDs) to the given space by (legacy) compatID
+CGError CGSSetWindowListWorkspace(CGSConnectionID connection,
+                                  CGWindowID *windowIds,
```
Comment (kasper) [inline Phoenix/PHSpace.m:83]: Is this a single window ID or an array ref?

File: Phoenix/PHSpace.m [hunk 4]
```diff
@@ -61,8 +65,25 @@ @implementation PHSpace
...
+                                  NSUInteger windowCount,
+                                  NSUInteger compatID);
```
Comment (kasper) [inline Phoenix/PHSpace.m:85]:
```suggestion
                                  NSUInteger compatId);
```

File: Phoenix/PHSpace.m [hunk 5]
```diff
@@ -223,8 +244,23 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
 }
 
 - (void)moveWindows:(NSArray<PHWindow *> *)windows {
-    CGSMoveWindowsToManagedSpace(
-        CGSMainConnectionID(), (__bridge CFArrayRef)[self identifiersForWindows:windows], self.identifier);
+    CGSConnectionID cid = CGSMainConnectionID();
+    if ([NSProcessInfo canMoveWindowsToManagedSpace]) {
```
Comment (kasper) [inline Phoenix/PHSpace.m:248]: Let’s reverse this conditional after renaming the method.

File: Phoenix/PHSpace.m [hunk 6]
```diff
@@ -223,8 +244,23 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
...
+        CGSMoveWindowsToManagedSpace(cid, (__bridge CFArrayRef)[self identifiersForWindows:windows], self.identifier);
+        return;
+    }
+
```
Comment (kasper) [inline Phoenix/PHSpace.m:252]: Can you split the workaround to a separate private method to increase readability?

File: Phoenix/PHSpace.m [hunk 7]
```diff
@@ -223,8 +244,23 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
...
+    NSArray<NSNumber *> *ids = [self identifiersForWindows:windows];
+    NSUInteger numIds = [ids count];
```
Comment (kasper) [inline Phoenix/PHSpace.m:254]: Right?

```suggestion
    NSUInteger windowCount = [ids count];
```

File: Phoenix/PHSpace.m (hunk 3 above)
Comment (kasper) [reply Phoenix/PHSpace.m:83]: Or well I guess it’s the ID sequence, but the type or naming seems confusing.

File: Phoenix/PHSpace.m [hunk 8]
```diff
@@ -223,8 +244,23 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
...
+    NSMutableData *contiguousIds = [[NSMutableData alloc] initWithCapacity:numIds * sizeof(CGWindowID)];
```
Comment (kasper) [inline Phoenix/PHSpace.m:255]: Might make more sense?

```suggestion
    NSMutableData *windowIdSequence = [[NSMutableData alloc] initWithCapacity:numIds * sizeof(CGWindowID)];
```

File: Phoenix/PHSpace.m [hunk 9]
```diff
@@ -223,8 +244,23 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
 }
 
 - (void)moveWindows:(NSArray<PHWindow *> *)windows {
-    CGSMoveWindowsToManagedSpace(
-        CGSMainConnectionID(), (__bridge CFArrayRef)[self identifiersForWindows:windows], self.identifier);
+    CGSConnectionID cid = CGSMainConnectionID();
```
Comment (kasper) [inline Phoenix/PHSpace.m:247]:
```suggestion
    CGSConnectionID connection = CGSMainConnectionID();
```

File: Phoenix/PHSpace.m [hunk 10]
```diff
@@ -223,8 +244,23 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
...
+    NSUInteger numIds = [ids count];
+    NSMutableData *contiguousIds = [[NSMutableData alloc] initWithCapacity:numIds * sizeof(CGWindowID)];
+    for (id item in ids) {
+        CGWindowID value = [item unsignedIntValue];
+        [contiguousIds appendBytes:&value length:sizeof(CGWindowID)];
+    }
+
+    CGSSpaceSetCompatID(cid, self.identifier, MoveWindowsCompatId);
+    CGSSetWindowListWorkspace(cid, (CGWindowID *)[contiguousIds bytes], numIds, MoveWindowsCompatId);
+    CGSSpaceSetCompatID(cid, self.identifier, 0x0);
```
Comment (kasper) [inline Phoenix/PHSpace.m:263]: What is the `0x0` for?

File: Phoenix/PHSpace.m [hunk 11]
```diff
@@ -36,6 +37,9 @@ @implementation PHSpace
 static NSString *const CGSSpaceIDKey = @"ManagedSpaceID";
 static NSString *const CGSSpacesKey = @"Spaces";
 
+// An arbitrary ID we can use CGSMoveWindowsToManagedSpace with.
+const NSUInteger MoveWindowsCompatId = 0x79616265;
```
[the remark this answers is not in the document]
Comment (kasper) [reply Phoenix/PHSpace.m:41]: Couldn’t we typedef this as `CGSMoveWindowCompatID` or something?

File: Phoenix/PHSpace.m (hunk 10 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m:263]: I copied it from the yabai and Amethyst fixes - I assume it's to unset the compat ID, but there's no clear documentation.

File: Phoenix/NSProcessInfo+PHExtension.h [hunk 12]
```diff
@@ -10,5 +10,6 @@
 
 + (BOOL)isOperatingSystemAtLeastBigSur;
 + (BOOL)isOperatingSystemAtLeastMonterey;
++ (BOOL)canMoveWindowsToManagedSpace;
```
[the remark this answers is not in the document]
Comment (metakirby5) [reply Phoenix/NSProcessInfo+PHExtension.h]: Done! Had to invert the condition to match the name.

File: Phoenix/PHSpace.m (hunk 11 above)
[the remark this answers is not in the document]
Comment (metakirby5) [reply Phoenix/PHSpace.m]: >Can you make this static?

I didn't know static worked that way in Objective C, cool - done!

>Do we need this to be a hex value?

My guess is that it's an arbitrary ID, but I'm not sure if there's anything special about it - it's just the same one from the yabai and Amethyst fixes, and I figured it would be most consistent to use the same one.

>Couldn’t we typedef this as `CGSMoveWindowCompatID` or something?

I'm not sure if that's the official name, but happy to!

File: Phoenix/PHSpace.m (hunk 2 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Done!

File: Phoenix/PHSpace.m [hunk 13]
```diff
@@ -36,6 +37,9 @@ @implementation PHSpace
 static NSString *const CGSSpaceIDKey = @"ManagedSpaceID";
 static NSString *const CGSSpacesKey = @"Spaces";
 
+// An arbitrary ID we can use CGSMoveWindowsToManagedSpace with.
```
[the remark this answers is not in the document]
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Done!

File: Phoenix/PHSpace.m (hunk 1 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Done!

File: Phoenix/PHSpace.m [hunk 14]
```diff
@@ -61,8 +65,25 @@ @implementation PHSpace
...
+ * The two functions below serve as a workaround to CGSMoveWindowsToManagedSpace breaking in MacOS 14.5.
+ * - https://github.com/kasper/phoenix/issues/348
+ * - https://github.com/koekeishiya/yabai/issues/2240#issuecomment-2116326165
+ * - https://github.com/ianyh/Amethyst/issues/1643#issuecomment-2132519682
+ */
+
+// XXX: Undocumented private API to set a space's (legacy) compatID
+CGError CGSSpaceSetCompatID(CGSConnectionID connection, CGSSpaceID spaceId, NSUInteger compatID);
+
+// XXX: Undocumented private API to move the given windows (CGWindowIDs) to the given space by (legacy) compatID
```
[the remark this answers is not in the document]
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Done!

File: Phoenix/PHSpace.m (hunk 9 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Done!

File: Phoenix/PHSpace.m (hunk 7 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Done!

File: Phoenix/PHSpace.m (hunk 6 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m:246]: Done!

File: Phoenix/PHSpace.m (hunk 5 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Done!

File: Phoenix/PHSpace.m (hunk 4 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Done!

File: Phoenix/PHSpace.m (hunk 3 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m:77]: My understanding is that it's a pointer to an int ID array, which in C would just be a contiguous block of memory. I'm not sure what the idiomatic way of naming and converting/passing it into the API is in Objective C, so I'm happy to make any change you think will improve clarity!

Comment (metakirby5) [reply Phoenix/PHSpace.m:77]: Changed to `CGWindowID windowIds[]` since I think that is at least clearer.

Comment (kasper) [reply Phoenix/PHSpace.m]: Out of curiosity, could you try making this `CFArrayRef windowIds`, then you could also try just to create a normal mutable array (https://github.com/kasper/phoenix/blob/b8f8f277a8a4435aff265fdc58135233c2310eef/Phoenix/PHSpace.m#L189) and bridge it as an array ref (https://github.com/kasper/phoenix/blob/b8f8f277a8a4435aff265fdc58135233c2310eef/Phoenix/PHSpace.m#L209). Would this work?

File: Phoenix/PHSpace.m [hunk 15]
```diff
@@ -61,8 +66,18 @@ @implementation PHSpace
 void CGSRemoveWindowsFromSpaces(CGSConnectionID connection, CFArrayRef windowIds, CFArrayRef spaceIds);
 
 // XXX: Undocumented private API to move the given windows (CGWindowIDs) to the given space
+//      Only works prior to MacOS 14.5!
 void CGSMoveWindowsToManagedSpace(CGSConnectionID connection, CFArrayRef windowIds, CGSSpaceID spaceId);
 
+// XXX: Undocumented private API to set a space’s (legacy) compatId
+CGError CGSSpaceSetCompatID(CGSConnectionID connection, CGSSpaceID spaceId, CGSMoveWindowCompatID compatID);
```
Comment (kasper) [inline Phoenix/PHSpace.m:73]:
```suggestion
CGError CGSSpaceSetCompatID(CGSConnectionID connection, CGSSpaceID spaceId, CGSMoveWindowCompatID compatId);
```

File: Phoenix/PHSpace.m [hunk 16]
```diff
@@ -223,8 +238,34 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
...
+    // CGSMoveWindowsToManagedSpace is broken in MacOS 14.5, so use the legacy Compat ID API instead.
+    [self moveWindowsWithCompatId:windows];
+}
+
+/**
+ * - https://github.com/kasper/phoenix/issues/348
+ * - https://github.com/koekeishiya/yabai/issues/2240#issuecomment-2116326165
+ * - https://github.com/ianyh/Amethyst/issues/1643#issuecomment-2132519682
+ */
+- (void)moveWindowsWithCompatId:(NSArray<PHWindow *> *)windows {
```
Comment (kasper) [inline Phoenix/PHSpace.m:256]: Can you move this method before `moveWindows`? I prefer having functions being defined in logical order.

Comment (metakirby5) [reply Phoenix/PHSpace.m:245]: Done!

File: Phoenix/PHSpace.m (hunk 15 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Oops, missed this one. Fixed!

File: Phoenix/PHSpace.m (hunk 3 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: I tried this:

```objectivec
- (void)moveWindowsWithCompatId:(NSArray<PHWindow *> *)windows {
    NSArray<NSNumber *> *ids = [self identifiersForWindows:windows];
    CGSConnectionID connection = CGSMainConnectionID();
    CGSSpaceSetCompatID(connection, self.identifier, MoveWindowsCompatId);
    CGSSetWindowListWorkspace(connection, (__bridge CFArrayRef)ids, [ids count], MoveWindowsCompatId);
    CGSSpaceSetCompatID(connection, self.identifier, 0x0);
}
```

Unfortunately, it doesn't work - I think the API expects a C-style array where values are stored in contiguous memory, and `NS(Mutable)Array` have no such guarantees.

Comment (kasper) [reply Phoenix/PHSpace.m]: Yep, I was just mostly curious. Thanks! 😄

File: Phoenix/PHSpace.m [hunk 17]
```diff
@@ -36,6 +38,9 @@ @implementation PHSpace
 static NSString *const CGSSpaceIDKey = @"ManagedSpaceID";
 static NSString *const CGSSpacesKey = @"Spaces";
 
+// An arbitrary ID we can use with CGSSpaceSetCompatID
+static const CGSMoveWindowCompatID MoveWindowsCompatId = 0x79616265;
```
Comment (kasper) [inline Phoenix/PHSpace.m:42]:
```suggestion
static const CGSMoveWindowCompatID PHMoveWindowsCompatId = 0x79616265;
```

File: Phoenix/PHSpace.m [hunk 18]
```diff
@@ -61,8 +66,18 @@ @implementation PHSpace
 void CGSRemoveWindowsFromSpaces(CGSConnectionID connection, CFArrayRef windowIds, CFArrayRef spaceIds);
 
 // XXX: Undocumented private API to move the given windows (CGWindowIDs) to the given space
```
Comment (kasper) [inline Phoenix/PHSpace.m:68]:
```suggestion
// XXX: Undocumented private API to move the given windows (CGWindowIDs) to the given space, only works prior to macOS 14.5
```

File: Phoenix/PHSpace.m [hunk 19]
```diff
@@ -222,9 +237,35 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
                                (__bridge CFArrayRef) @[@(self.identifier)]);
 }
 
+/**
+ * - https://github.com/kasper/phoenix/issues/348
+ * - https://github.com/koekeishiya/yabai/issues/2240#issuecomment-2116326165
+ * - https://github.com/ianyh/Amethyst/issues/1643#issuecomment-2132519682
+ */
+- (void)moveWindowsWithCompatId:(NSArray<PHWindow *> *)windows {
+    NSArray<NSNumber *> *ids = [self identifiersForWindows:windows];
```
Comment (kasper) [inline Phoenix/PHSpace.m:246]:
```suggestion
    NSArray<NSNumber *> *windowIds = [self identifiersForWindows:windows];
```

File: Phoenix/PHSpace.m [hunk 20]
```diff
@@ -222,9 +237,35 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
...
+    NSUInteger windowCount = [ids count];
+    NSMutableData *windowIdSequence = [[NSMutableData alloc] initWithCapacity:windowCount * sizeof(CGWindowID)];
+    for (id item in ids) {
```
Comment (kasper) [inline Phoenix/PHSpace.m:249]: Type as `NSNumber` instead of `id`.

File: Phoenix/PHSpace.m [hunk 21]
```diff
@@ -222,9 +237,35 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
...
+        CGWindowID value = [item unsignedIntValue];
```
Comment (kasper) [inline Phoenix/PHSpace.m:250]: Then you can:

```suggestion
        CGWindowID value = item.unsignedIntValue;
```

File: Phoenix/PHSpace.m [hunk 22]
```diff
@@ -222,9 +237,35 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
...
+    CGSConnectionID connection = CGSMainConnectionID();
+    CGSSpaceSetCompatID(connection, self.identifier, MoveWindowsCompatId);
+    CGSSetWindowListWorkspace(connection, (CGWindowID *)[windowIdSequence bytes], windowCount, MoveWindowsCompatId);
+    CGSSpaceSetCompatID(connection, self.identifier, 0x0);
+}
+
 - (void)moveWindows:(NSArray<PHWindow *> *)windows {
-    CGSMoveWindowsToManagedSpace(
-        CGSMainConnectionID(), (__bridge CFArrayRef)[self identifiersForWindows:windows], self.identifier);
+    if (![NSProcessInfo isOperatingSystemAtLeastSonoma145]) {
```
Comment (kasper) [inline Phoenix/PHSpace.m:261]: I would still revert this conditional. Exception case first.

File: Phoenix/PHSpace.m [hunk 23]
```diff
@@ -222,9 +237,35 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
...
+        CGSMoveWindowsToManagedSpace(
+            CGSMainConnectionID(), (__bridge CFArrayRef)[self identifiersForWindows:windows], self.identifier);
+        return;
+    }
+
+    // CGSMoveWindowsToManagedSpace is broken in MacOS 14.5, so use the legacy Compat ID API instead.
```
Comment (kasper) [inline Phoenix/PHSpace.m:267]: Then move this comment before the conditional.

```suggestion
    // CGSMoveWindowsToManagedSpace is broken in macOS 14.5, so use the legacy Compat ID API instead
```

**Review by kasper — COMMENTED** [review]
Alright, last set of comments, sorry! Looks good to me after that. ❤️

File: Phoenix/PHSpace.m (hunk 22 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m:261]: IMO the exception case _is_ first, because versions of macOS < 14.5 will never increase, and versions of macOS >= 14.5 always increase 🤔 So to align with the intent of your comment, I'll keep the existing order.

File: Phoenix/PHSpace.m (hunk 17 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Done!

File: Phoenix/PHSpace.m (hunk 18 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Done! `clang-format` demands it be broken up into two lines though,  so I added a line break after the comma.

File: Phoenix/PHSpace.m (hunk 19 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Done!

File: Phoenix/PHSpace.m (hunk 20 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: I get the compile error `Interface type cannot be statically allocated`; I think it needs to be `NSNumber *` (which is the type of the array item). Changed to that!

File: Phoenix/PHSpace.m (hunk 21 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: Done!

File: Phoenix/PHSpace.m (hunk 23 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: As mentioned in https://github.com/kasper/phoenix/pull/350#discussion_r1632003998, I think keeping the order better aligns with your intent, but adopted the comment style changes 👀

File: Phoenix/PHSpace.m [hunk 24]
```diff
@@ -222,9 +237,35 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
...
+/**
+ * - https://github.com/kasper/phoenix/issues/348
+ * - https://github.com/koekeishiya/yabai/issues/2240#issuecomment-2116326165
+ * - https://github.com/ianyh/Amethyst/issues/1643#issuecomment-2132519682
+ */
+- (void)moveWindowsWithCompatId:(NSArray<PHWindow *> *)windows {
+    NSArray<NSNumber *> *windowIds = [self identifiersForWindows:windows];
+    NSUInteger windowCount = [windowIds count];
+    NSMutableData *windowIdSequence = [[NSMutableData alloc] initWithCapacity:windowCount * sizeof(CGWindowID)];
+    for (NSNumber *item in windowIds) {
```
Comment (kasper) [inline Phoenix/PHSpace.m:249]:
```suggestion
    for (NSNumber *windowId in windowIds) {
```

File: Phoenix/PHSpace.m [hunk 25]
```diff
@@ -222,9 +237,35 @@ - (void)removeWindows:(NSArray<PHWindow *> *)windows {
...
+        CGWindowID value = item.unsignedIntValue;
```
Comment (kasper) [inline Phoenix/PHSpace.m:250]:
```suggestion
        CGWindowID value = windowId.unsignedIntValue;
```

**Review by kasper — DISMISSED** [review]
Thanks!

File: Phoenix/PHSpace.m (hunk 24 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: ✅

File: Phoenix/PHSpace.m (hunk 25 above)
Comment (metakirby5) [reply Phoenix/PHSpace.m]: ✅

**Review by kasper — APPROVED** [review]

**Comment by metakirby5** [comment]
@kasper Thanks for approving! I don't have permission to merge, so can you do so for me? 🙏

**Comment by kasper** [comment]
@metakirby5 Thanks, merged! I will try to get this released soon. I want to update all the dependencies while at it.

**Comment by dan-phantom** [comment]
Just x-posing here, maybe it gets visible? 😅

https://github.com/kasper/phoenix/issues/348#issuecomment-2182162242

**Comment by kasper** [comment]
@dan-phantom Hey, thanks for the ping! Let’s continue in #351.
